package com.techlads.jetsleepsounds.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF754B9C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF0DBFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2C0050)
val md_theme_light_secondary = Color(0xFF665A6F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEDDDF6)
val md_theme_light_onSecondaryContainer = Color(0xFF211829)
val md_theme_light_tertiary = Color(0xFF805157)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9DC)
val md_theme_light_onTertiaryContainer = Color(0xFF321016)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE9DFEB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFF7C757E)
val md_theme_light_inverseOnSurface = Color(0xFFF6EFF4)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFDEB7FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF754B9C)
val md_theme_light_outlineVariant = Color(0xFFCDC4CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDEB7FF)
val md_theme_dark_onPrimary = Color(0xFF44196A)
val md_theme_dark_primaryContainer = Color(0xFF5C3383)
val md_theme_dark_onPrimaryContainer = Color(0xFFF0DBFF)
val md_theme_dark_secondary = Color(0xFFD0C1D9)
val md_theme_dark_onSecondary = Color(0xFF372C3F)
val md_theme_dark_secondaryContainer = Color(0xFF4E4356)
val md_theme_dark_onSecondaryContainer = Color(0xFFEDDDF6)
val md_theme_dark_tertiary = Color(0xFFF3B7BD)
val md_theme_dark_onTertiary = Color(0xFF4B252A)
val md_theme_dark_tertiaryContainer = Color(0xFF653A40)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE7E1E5)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE7E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC4CE)
val md_theme_dark_outline = Color(0xFF968E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val md_theme_dark_inversePrimary = Color(0xFF754B9C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDEB7FF)
val md_theme_dark_outlineVariant = Color(0xFF4A454E)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF754C9C)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

/**
 * Gray white theme, file is available in app folder
 */

val light = Color(0xFFe8e8e7)
val dark = Color(0xFF4c586b)
val darkVariant = Color(0xFF6b7688)
val surface = Color(0xFF8a95a5)
val surfaceVariant = Color(0xFFaab4c3)